import os
import json
import hashlib
from datetime import datetime, timedelta
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))
MODEL = "llama-3.1-8b-instant"
CACHE_FILE = "cache.json"

def _load_cache():
    try:
        with open(CACHE_FILE, "r") as f:
            return json.load(f)
    except:
        return {}

def _save_cache(cache):
    with open(CACHE_FILE, "w") as f:
        json.dump(cache, f)

def _get_key(prompt):
    return hashlib.md5(prompt.encode()).hexdigest()[:16]

def _call_groq(system_prompt, user_prompt):
    cache = _load_cache()
    key = _get_key(system_prompt + user_prompt)
    if key in cache:
        return cache[key]
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=0.7,
        max_tokens=3000
    )
    result = response.choices[0].message.content
    cache[key] = result
    _save_cache(cache)
    return result

def run_trip_planner(destination, duration, budget, currency, preferences, start_date=None, travelers=2):
    # Build date context
    date_context = ""
    date_header = ""
    if start_date:
        try:
            start = datetime.strptime(start_date, "%Y-%m-%d")
            dates = [(start + timedelta(days=i)).strftime("%A, %B %d, %Y") for i in range(duration)]
            date_context = "Use these EXACT dates for each day:\n" + "\n".join([f"Day {i+1}: {d}" for i, d in enumerate(dates)])
            end = start + timedelta(days=duration-1)
            date_header = f"**Dates:** {start.strftime('%B %d, %Y')} to {end.strftime('%B %d, %Y')}"
        except:
            pass
    
    per_person = budget // travelers if travelers > 0 else budget
    
    research = _call_groq(
        "You are a seasoned travel blogger.",
        f"Research {destination} for {duration} days. Traveler likes: {preferences}. Group of {travelers} people. Top 10 attractions, 5 restaurants, transport tips for groups. Be specific."
    )

    itinerary = _call_groq(
        "You are a logistics genius.",
        f"""Day-by-day itinerary for {duration} days in {destination} for {travelers} travelers.
{date_context}

Research: {research}
Group nearby spots. 9 AM start, 9 PM end. Include meal times.
Recommend group-friendly transport and accommodations.
If dates are provided above, use them as headers instead of 'Day 1'."""
    )

    budget_analysis = _call_groq(
        "You are a travel accountant. Realistic 2026 prices.",
        f"""Costs in {currency} for {duration} days in {destination} for {travelers} travelers.
Itinerary: {itinerary}
Total budget: {budget} {currency} ({per_person} {currency} per person).

Break down:
- Accommodation (suggest room configuration for {travelers} people)
- Food (per person per meal)
- Group transport
- Activities/entrance fees
- Emergency buffer (10%)

Compare to budget. Suggest savings if over."""
    )

    packing = _call_groq(
        "You are a practical travel expert.",
        f"""Create a packing list for {travelers} travelers going to {destination} for {duration} days.
Activities from itinerary: {itinerary}
Preferences: {preferences}

Categorize: Clothing, Toiletries, Electronics, Documents, Health, Extras.
Be specific and practical."""
    )

    return f"""
# Travel Plan: {destination}

> **{duration} days** | **{travelers} travelers** | **Budget:** {budget} {currency} (~{per_person} per person) | **Style:** {preferences}
> {date_header}

---

## Research & Top Attractions
{research}

---

## Day-by-Day Itinerary
{itinerary}

---

## Budget Analysis
{budget_analysis}

---

## Packing List
{packing}

---
*Generated by TravelAgent AI*
"""