import os
import json
import hashlib
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# 8B model = 10x cheaper on tokens than 70B
MODEL = "llama-3.1-8b-instant"

# ─── File Cache (never burn tokens twice) ────────────────
CACHE_FILE = "cache.json"

def _load_cache():
    try:
        with open(CACHE_FILE, "r") as f:
            return json.load(f)
    except:
        return {}

def _save_cache(cache):
    with open(CACHE_FILE, "w") as f:
        json.dump(cache, f)

def _get_key(prompt):
    return hashlib.md5(prompt.encode()).hexdigest()[:16]

def _call_groq(system_prompt, user_prompt):
    cache = _load_cache()
    key = _get_key(system_prompt + user_prompt)
    
    if key in cache:
        return cache[key]
    
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=0.7,
        max_tokens=3000
    )
    
    result = response.choices[0].message.content
    cache[key] = result
    _save_cache(cache)
    return result

# ─── Agents ──────────────────────────────────────────────
def run_trip_planner(destination, duration, budget, currency, preferences):
    research = _call_groq(
        "You are a seasoned travel blogger.",
        f"Research {destination} for {duration} days. Traveler likes: {preferences}. Top 10 attractions, 5 restaurants, transport tips. Be specific."
    )

    itinerary = _call_groq(
        "You are a logistics genius.",
        f"Day-by-day itinerary for {duration} days in {destination}. Research: {research}. Group nearby spots. 9 AM start, 9 PM end."
    )

    budget_analysis = _call_groq(
        "You are a travel accountant. Realistic 2026 prices.",
        f"Costs in {currency} for {duration} days in {destination}. Itinerary: {itinerary}. Hotel, Food, Transport, Activities, 10% buffer. Budget: {budget} {currency}."
    )

    return f"""
# Travel Plan: {destination}

> **{duration} days** | **Budget:** {budget} {currency} | **Style:** {preferences}

---

## Research & Top Attractions
{research}

---

## Day-by-Day Itinerary
{itinerary}

---

## Budget Analysis
{budget_analysis}

---
*Generated by TravelAgent AI*
"""