import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))
MODEL = "llama-3.3-70b-versatile"

def _call_groq(system_prompt, user_prompt):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=0.7,
        max_tokens=4000
    )
    return response.choices[0].message.content

def _plan_single_city(city, days, preferences, total_budget, currency):
    """Run all 3 agents for ONE city."""
    
    # Agent 1: Research
    research = _call_groq(
        "You are a seasoned travel blogger.",
        f"""Research {city} for a {days}-day trip. Traveler likes: {preferences}.
Find top attractions, restaurants, transport. Be specific with names and neighborhoods."""
    )
    
    # Agent 2: Planner
    itinerary = _call_groq(
        "You are a logistics genius.",
        f"""Create a day-by-day itinerary for {days} days in {city}.
Research: {research}
Group nearby spots. 9 AM start, 9 PM end. Include specific restaurant names."""
    )
    
    # Agent 3: Budget (with realistic estimates)
    budget = _call_groq(
        "You are a travel accountant. Use realistic 2026 prices.",
        f"""Estimate costs for {days} days in {city} in {currency}.
Itinerary: {itinerary}
Be realistic: mid-range hotel ~$80-150/night, meals ~$15-40, transport ~$10-30/day.
Total budget limit for this city: ~{int(total_budget)} {currency}.
Break down: Hotel, Food, Transport, Activities, Buffer."""
    )
    
    return research, itinerary, budget

def run_trip_planner(destination, duration, budget, currency, preferences):
    """
    destination can be: "Paris" OR "Paris, Rome, Dubai"
    """
    cities = [c.strip() for c in destination.split(',')]
    
    # Single city (original behavior)
    if len(cities) == 1:
        research, itinerary, budget_analysis = _plan_single_city(
            cities[0], duration, preferences, budget, currency
        )
        
        return f"""
# Travel Plan: {cities[0]}

> **{duration} days** | **Budget:** {budget} {currency} | **Style:** {preferences}

---

## Research & Top Attractions
{research}

---

## Day-by-Day Itinerary
{itinerary}

---

## Budget Analysis
{budget_analysis}

---
*Generated by TravelAgent AI*
"""
    
    # Multi-city mode
    days_per_city = max(1, duration // len(cities))
    remaining_days = duration - (days_per_city * len(cities))
    budget_per_city = budget // len(cities)
    
    all_plans = []
    total_spent = 0
    
    for i, city in enumerate(cities):
        # Give extra day to first city
        city_days = days_per_city + (1 if i < remaining_days else 0)
        
        st.info(f"Planning {city} ({city_days} days)...") if 'st' in globals() else None
        
        research, itinerary, city_budget = _plan_single_city(
            city, city_days, preferences, budget_per_city, currency
        )
        
        all_plans.append({
            "city": city,
            "days": city_days,
            "research": research,
            "itinerary": itinerary,
            "budget": city_budget
        })
    
    # Build combined output
    sections = [f"# Multi-City Adventure: {' → '.join(cities)}\n\n> **{duration} days total** | **Budget:** {budget} {currency}\n"]
    
    # Transport between cities
    transport = _call_groq(
        "You are a transport logistics expert.",
        f"""Suggest transport between these cities: {' → '.join(cities)}.
For each leg, recommend: flight vs train vs bus, estimated price in {currency}, duration.
Be realistic with 2026 prices."""
    )
    
    sections.append(f"## Transport Between Cities\n{transport}\n")
    
    # Each city
    for plan in all_plans:
        sections.append(f"""
---

## {plan['city']} ({plan['days']} days)

### Research
{plan['research']}

### Itinerary
{plan['itinerary']}

### Budget
{plan['budget']}
""")
    
    sections.append(f"\n---\n*Generated by TravelAgent AI — Multi-City Planner*")
    
    return "\n".join(sections)

if __name__ == "__main__":
    # Test multi-city
    result = run_trip_planner(
        destination="Paris, Rome, Dubai",
        duration=10,
        budget=3000,
        currency="USD",
        preferences="luxury hotels, fine dining, photography"
    )
    print(result)